apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: projects
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
        - name: microapp-projects
          image: faridmansimli/microapp-projects
          ports:
            - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: projects-srv
spec:
  type: ClusterIP
  selector:
    app: projects
  ports:
    - name: projects
      protocol: TCP
      port: 4001
      targetPort: 4001
