apiVersion: apps/v1
kind: Deployment
metadata:
  name: microapp-projects-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microapp-projects
  template:
    metadata:
      labels:
        app: microapp-projects
    spec:
      containers:
        - name: microapp-projects
          image: faridmansimli/microapp-projects
          env:
            - name: KAFKA_URL
              value: 'http://kafka-srv:9092'

            - name: KAFKA_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
        
            - name: JWT_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_KEY

          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4001
---
apiVersion: v1
kind: Service
metadata:
  name: microapp-projects-srv
spec:
  type: ClusterIP
  selector:
    app: microapp-projects
  ports:
    - name: microapp-projects
      protocol: TCP
      port: 4001
      targetPort: 4001
