apiVersion: apps/v1
kind: Deployment
metadata:
  name: microapp-teams-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: microapp-teams
  template:
    metadata:
      labels:
        app: microapp-teams
    spec:
      containers:
        - name: microapp-teams
          image: faridmansimli/microapp-teams
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: microapp-teams-srv
spec:
  type: ClusterIP
  selector:
    app: microapp-teams
  ports:
    - name: microapp-teams
      protocol: TCP
      port: 4002
      targetPort: 4002
