name: Test and Deploy the Payment microservice
on:
  push:
    branches:
      - "production"
      - "prod-*"
      - "prod/**"
    paths:
      - "payment/**"

  workflow_dispatch:

env:
  TEST_VARIABLE: "test-variable"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Login to Docker hub
        run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

      - name: Build docker image
        run: cd auth && docker build -t faridmansimli/microapp-payment .
      
      - name: Push the image to Docker hub
        run: cd auth && docker push faridmansimli/microapp-payment

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: $DIGITALOCEAN_ACCESS_TOKEN
      
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save microapp-cluster

      - name: Restart the auth deployment (payment-depl.yaml)
        run: kubectl rollout restart deployment payment-depl
      
      - name: Finish the process
        run: echo "microapp-payment deployment successfull!"