name: Deploy manifests
on:
  push:
    branches:
      - "production"
    paths:
      - "infra/k8s-prod/**"
      - "infra/k8s/**"

  workflow_dispatch:

env:
  TEST_VARIABLE: "test-variable"

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DIGITALOCEAN_ACCESS_TOKEN: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
    steps:
      - name: Get code
        uses: actions/checkout@v3

      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: $DIGITALOCEAN_ACCESS_TOKEN
      
      - name: Save DigitalOcean kubeconfig
        run: doctl kubernetes cluster kubeconfig save microapp-cluster

      - name: Apply all deployments and other kube objects to the cluster
        run: kubectl apply -f infra/k8s && kubectl apply -f infra/k8s-prod
      
      - name: Finish the process
        run: echo "applying of manifests is successfull!"